version: '3.6'

services:
  frontend:
    build: ./
    container_name: skillkit_frontend
    env_file:
      - .env
    hostname: skillkit_frontend
    expose:
      - ${PORT:-3000}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    restart: unless-stopped
    networks:
      - external_network
    external_links:
      - skillkit_backend_prod

networks:
  external_network:
    external:
      name: skillkit_network
