version: '3.6'

services:
  frontend:
    build:
      context: ./
      args:
        - API_HOST=localhost
        - API_PORT=3000
    container_name: gamelab_frontend
    env_file:
      - .env
    hostname: gamelab_frontend
    networks: 
      - gamelab_default
    expose:
      - 3000
    ports:
      - '3000:3000'
    restart: unless-stopped

networks:
  gamelab_default: