version: '3.6'

services:
  frontend:
    build: ./
    container_name: skillkit_frontend
    env_file:
      - .env
    hostname: skillkit_frontend
    expose:
      - ${PORT:-3000}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    restart: unless-stopped
    networks:
      - skillkit_network
