import React, { ReactElement, useState } from 'react';
import ProtectedLayout from '@layouts/ProtectedLayout';
import { NextPageWithLayout } from '@pages/_app';
import { ProjectQuery } from '@services/graphql/queries/project';
import { RootState } from '@store/configure-store';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useSelector } from 'react-redux';
import { useQuery } from 'urql';

const ProjectPage: NextPageWithLayout = () => {
	const router = useRouter();
	const { id } = router.query;
	const [{ data: projectData, fetching: projectFetching, error: projectError }, reexecuteProject] = useQuery({
		query: ProjectQuery,
		variables: { id },
	});

	return (
		<>
			<Head>
				<title>Project</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>{projectData?.project.title}</h1>
			<p>
				{projectData?.project.genre}, {projectData?.project.platforms}
			</p>
		</>
	);
};

ProjectPage.getLayout = (page: ReactElement) => <ProtectedLayout title="Project">{page}</ProtectedLayout>;

export default ProjectPage;
