import type { NextPage } from 'next'
import Head from 'next/head'

const AboutPage: NextPage = () => {
    return (
        <>
            <Head>
                <title>About page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>About page</main>
        </>
    )
}

export default AboutPage
