import React, { ReactElement } from 'react'
import { SettingsMenu } from '@components/menus/SettingsMenu';
import { NextPageWithLayout } from '@pages/_app'
import ProtectedLayout from 'src/layouts/ProtectedLayout'
import { Col, Row } from 'antd';
import Head from 'next/head'
import styles from './SecurityPage.module.less';

const SecurityPage: NextPageWithLayout = () => {
    return (
        <>
            <Head>
                <title>Security</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Row>
                <Col>
                    <SettingsMenu selectedItem="security" />
                </Col>
                <Col flex="1" className={styles.contentSection}>
                    asdad34
                </Col>
            </Row>
        </>
    )
}

SecurityPage.getLayout = (page: ReactElement) => <ProtectedLayout title="Profile">{page}</ProtectedLayout>;

export default SecurityPage;