import { ReactElement } from 'react'
import { NextPageWithLayout } from '@pages/_app'
import ProtectedLayout from 'src/layouts/ProtectedLayout'
import { Col, Row } from 'antd';
import Head from 'next/head'

const ProfilePage: NextPageWithLayout = () => {
    return (
        <>
            <Head>
                <title>Profile</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Row>
                <Col flex="250px">
                    Profile
                </Col>
                <Col flex="1">
                    Form
                </Col>
            </Row>
        </>
    )
}

ProfilePage.getLayout = (page: ReactElement) => <ProtectedLayout title="Profile">{page}</ProtectedLayout>;

export default ProfilePage;