# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Staging Workflow

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: add next # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint # will run `yarn lint` command
        env:
          NEXT_PUBLIC_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
          NEXT_PUBLIC_AUTH_COOKIE_NAME: ${{ secrets.NEXT_PUBLIC_AUTH_COOKIE_NAME }}
          NEXT_PUBLIC_IMAGES_HOST: ${{ secrets.NEXT_PUBLIC_IMAGES_HOST }}
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command
        env:
          NEXT_PUBLIC_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
          NEXT_PUBLIC_AUTH_COOKIE_NAME: ${{ secrets.NEXT_PUBLIC_AUTH_COOKIE_NAME }}
          NEXT_PUBLIC_IMAGES_HOST: ${{ secrets.NEXT_PUBLIC_IMAGES_HOST }}
