# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Staging Workflow

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - run: npm install -g yarn
    - run: yarn install --frozen-lockfile
    - name: Set environment variables
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8000/api/graphql
          NEXT_PUBLIC_AUTH_COOKIE_NAME: gamelab-session
    - run: yarn lint
    - run: yarn build
